import type { UserRole } from "@/types/auth";
import type { ReporteDefinition, ReporteTipo } from "@/types/reportes";

export const reportDefinitions: ReporteDefinition[] = [
  {
    id: "resumen-por-estado",
    label: "Resumen por estado",
    description: "Cantidad y montos agrupados por estado del flujo.",
    roles: ["JEFE_APROBADOR", "NOMINA", "ADMIN"],
    supportsDateFilter: true,
    supportsDepartamento: true,
    supportsEstado: false,
    supportsAnio: false,
    supportsSoloCerradas: false,
  },
  {
    id: "legalizaciones-detalle",
    label: "Detalle de legalizaciones",
    description: "Listado completo exportable de legalizaciones.",
    roles: ["JEFE_APROBADOR", "NOMINA", "ADMIN"],
    supportsDateFilter: true,
    supportsDepartamento: true,
    supportsEstado: true,
    supportsAnio: false,
    supportsSoloCerradas: false,
  },
  {
    id: "gastos-por-categoria",
    label: "Gastos por categoría",
    description: "Consolidado de montos por tipo de gasto.",
    roles: ["JEFE_APROBADOR", "NOMINA", "ADMIN"],
    supportsDateFilter: true,
    supportsDepartamento: true,
    supportsEstado: true,
    supportsAnio: false,
    supportsSoloCerradas: false,
  },
  {
    id: "gastos-detalle",
    label: "Detalle de gastos",
    description: "Línea a línea para conciliación de nómina.",
    roles: ["NOMINA", "ADMIN"],
    supportsDateFilter: true,
    supportsDepartamento: false,
    supportsEstado: true,
    supportsAnio: false,
    supportsSoloCerradas: false,
  },
  {
    id: "resumen-financiero-empleado",
    label: "Resumen financiero por empleado",
    description: "Anticipos, gastos, reembolsos y devoluciones por persona.",
    roles: ["NOMINA", "ADMIN"],
    supportsDateFilter: true,
    supportsDepartamento: true,
    supportsEstado: false,
    supportsAnio: false,
    supportsSoloCerradas: true,
  },
  {
    id: "pendientes-aprobacion",
    label: "Pendientes de aprobación",
    description: "Legalizaciones en bandeja del jefe con días pendientes.",
    roles: ["JEFE_APROBADOR", "ADMIN"],
    supportsDateFilter: false,
    supportsDepartamento: false,
    supportsEstado: false,
    supportsAnio: false,
    supportsSoloCerradas: false,
  },
  {
    id: "pendientes-nomina",
    label: "Pendientes de nómina",
    description: "Legalizaciones aprobadas listas para cierre.",
    roles: ["NOMINA", "ADMIN"],
    supportsDateFilter: false,
    supportsDepartamento: false,
    supportsEstado: false,
    supportsAnio: false,
    supportsSoloCerradas: false,
  },
  {
    id: "legalizaciones-cerradas",
    label: "Legalizaciones cerradas",
    description: "Cierres de nómina en un periodo.",
    roles: ["NOMINA", "ADMIN"],
    supportsDateFilter: true,
    supportsDepartamento: true,
    supportsEstado: false,
    supportsAnio: false,
    supportsSoloCerradas: false,
  },
  {
    id: "gastos-sin-soporte",
    label: "Gastos sin soporte",
    description: "Gastos que requieren documento pero no lo tienen adjunto.",
    roles: ["JEFE_APROBADOR", "NOMINA", "ADMIN"],
    supportsDateFilter: true,
    supportsDepartamento: false,
    supportsEstado: true,
    supportsAnio: false,
    supportsSoloCerradas: false,
  },
  {
    id: "historial-auditoria",
    label: "Historial de auditoría",
    description: "Trazabilidad de cambios de estado.",
    roles: ["JEFE_APROBADOR", "NOMINA", "ADMIN"],
    supportsDateFilter: true,
    supportsDepartamento: false,
    supportsEstado: false,
    supportsAnio: false,
    supportsSoloCerradas: false,
  },
  {
    id: "volumen-mensual",
    label: "Volumen mensual",
    description: "Tendencia de legalizaciones y montos por mes.",
    roles: ["JEFE_APROBADOR", "NOMINA", "ADMIN"],
    supportsDateFilter: false,
    supportsDepartamento: true,
    supportsEstado: false,
    supportsAnio: true,
    supportsSoloCerradas: false,
  },
  {
    id: "tiempos-por-estado",
    label: "Tiempos por estado",
    description: "Horas en cada etapa del flujo (SLA operativo).",
    roles: ["NOMINA", "ADMIN"],
    supportsDateFilter: true,
    supportsDepartamento: false,
    supportsEstado: false,
    supportsAnio: false,
    supportsSoloCerradas: false,
  },
];

export type ReportColumnFormat = "text" | "money" | "date" | "datetime" | "estado" | "number";

export type ReportColumn = {
  key: string;
  label: string;
  format?: ReportColumnFormat;
};

export const reportColumns: Record<ReporteTipo, ReportColumn[]> = {
  "resumen-por-estado": [
    { key: "estado", label: "Estado", format: "estado" },
    { key: "cantidad", label: "Cantidad", format: "number" },
    { key: "totalAnticipos", label: "Anticipos", format: "money" },
    { key: "totalGastos", label: "Gastos", format: "money" },
    { key: "totalReembolsos", label: "Reembolsos", format: "money" },
    { key: "totalDevoluciones", label: "Devoluciones", format: "money" },
  ],
  "legalizaciones-detalle": [
    { key: "numero", label: "Número" },
    { key: "empleadoNombre", label: "Empleado" },
    { key: "departamento", label: "Departamento" },
    { key: "motivo", label: "Motivo" },
    { key: "fechaInicio", label: "Inicio", format: "date" },
    { key: "fechaFin", label: "Fin", format: "date" },
    { key: "estado", label: "Estado", format: "estado" },
    { key: "montoAnticipo", label: "Anticipo", format: "money" },
    { key: "totalGastos", label: "Gastos", format: "money" },
    { key: "saldoAnticipo", label: "Saldo", format: "money" },
  ],
  "gastos-por-categoria": [
    { key: "categoriaNombre", label: "Categoría" },
    { key: "cantidadGastos", label: "Gastos", format: "number" },
    { key: "totalMonto", label: "Total", format: "money" },
    { key: "promedioMonto", label: "Promedio", format: "money" },
  ],
  "gastos-detalle": [
    { key: "legalizacionNumero", label: "Legalización" },
    { key: "empleadoNombre", label: "Empleado" },
    { key: "categoriaNombre", label: "Categoría" },
    { key: "fechaGasto", label: "Fecha", format: "date" },
    { key: "descripcion", label: "Descripción" },
    { key: "monto", label: "Monto", format: "money" },
    { key: "validado", label: "Validado" },
    { key: "cantidadSoportes", label: "Soportes", format: "number" },
  ],
  "resumen-financiero-empleado": [
    { key: "empleadoNombre", label: "Empleado" },
    { key: "departamento", label: "Departamento" },
    { key: "monedaCodigo", label: "Moneda" },
    { key: "cantidadLegalizaciones", label: "Legalizaciones", format: "number" },
    { key: "totalAnticipos", label: "Anticipos", format: "money" },
    { key: "totalGastos", label: "Gastos", format: "money" },
    { key: "totalReembolsos", label: "Reembolsos", format: "money" },
    { key: "totalDevoluciones", label: "Devoluciones", format: "money" },
  ],
  "pendientes-aprobacion": [
    { key: "numero", label: "Número" },
    { key: "empleadoNombre", label: "Empleado" },
    { key: "motivo", label: "Motivo" },
    { key: "fechaInicio", label: "Inicio", format: "date" },
    { key: "fechaFin", label: "Fin", format: "date" },
    { key: "totalGastos", label: "Gastos", format: "money" },
    { key: "diasPendientes", label: "Días pend.", format: "number" },
  ],
  "pendientes-nomina": [
    { key: "numero", label: "Número" },
    { key: "empleadoNombre", label: "Empleado" },
    { key: "motivo", label: "Motivo" },
    { key: "totalGastos", label: "Gastos", format: "money" },
    { key: "totalReembolso", label: "Reembolso", format: "money" },
    { key: "totalDevolucion", label: "Devolución", format: "money" },
  ],
  "legalizaciones-cerradas": [
    { key: "numero", label: "Número" },
    { key: "empleadoNombre", label: "Empleado" },
    { key: "departamento", label: "Departamento" },
    { key: "totalGastos", label: "Gastos", format: "money" },
    { key: "totalReembolso", label: "Reembolso", format: "money" },
    { key: "totalDevolucion", label: "Devolución", format: "money" },
    { key: "closedAt", label: "Cerrada", format: "datetime" },
  ],
  "gastos-sin-soporte": [
    { key: "legalizacionNumero", label: "Legalización" },
    { key: "empleadoNombre", label: "Empleado" },
    { key: "categoriaNombre", label: "Categoría" },
    { key: "fechaGasto", label: "Fecha", format: "date" },
    { key: "descripcion", label: "Descripción" },
    { key: "monto", label: "Monto", format: "money" },
  ],
  "historial-auditoria": [
    { key: "legalizacionNumero", label: "Legalización" },
    { key: "empleadoNombre", label: "Empleado" },
    { key: "estadoAnterior", label: "Estado anterior", format: "estado" },
    { key: "estadoNuevo", label: "Estado nuevo", format: "estado" },
    { key: "usuarioNombre", label: "Usuario" },
    { key: "comentario", label: "Comentario" },
    { key: "createdAt", label: "Fecha", format: "datetime" },
  ],
  "volumen-mensual": [
    { key: "periodo", label: "Periodo" },
    { key: "cantidadLegalizaciones", label: "Legalizaciones", format: "number" },
    { key: "totalAnticipos", label: "Anticipos", format: "money" },
    { key: "totalGastos", label: "Gastos", format: "money" },
    { key: "cantidadCerradas", label: "Cerradas", format: "number" },
  ],
  "tiempos-por-estado": [
    { key: "legalizacionNumero", label: "Legalización" },
    { key: "empleadoNombre", label: "Empleado" },
    { key: "estado", label: "Estado", format: "estado" },
    { key: "inicioEstado", label: "Inicio", format: "datetime" },
    { key: "finEstado", label: "Fin", format: "datetime" },
    { key: "horasEnEstado", label: "Horas", format: "number" },
  ],
};

export function getReportDefinitionsForRole(rol: UserRole): ReporteDefinition[] {
  return reportDefinitions.filter((item) => item.roles.includes(rol) || rol === "ADMIN");
}
